In [17]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

In [18]:
df= pd.read_csv('zoo_data .csv')
print(df)

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...   
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1   
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0   
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0   
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0   

    1.7  
0     1  
1     4  
2     1  

In [19]:
target=df['1.7']
target.head(10)

0    1
1    4
2    1
3    1
4    1
5    1
6    4
7    4
8    1
9    1
Name: 1.7, dtype: int64

In [20]:
df2=df.copy()
print(df2)

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6  \
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0   
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1   
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1   
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...   
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1   
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0   
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1   
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0   
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0   

    1.7  
0     1  
1     4  
2     1  

In [21]:

df2 = df2.iloc[:, :-1]
print(df2)

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6
0   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
1   0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0
2   1  0    0    1    0    0    1    1    1    1    0    0  4    0    0    1
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
4   1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...
95  1  0    0    1    0    0    0    1    1    1    0    0  2    1    0    1
96  1  0    1    0    1    0    0    0    0    1    1    0  6    0    0    0
97  1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
98  0  0    1    0    0    0    0    0    0    1    0    0  0    0    0    0
99  0  1    1    0    1    0    0    0    1    1    0    0  2    1    0    0

[100 rows x 16 columns]


In [22]:
X_train, X_test, y_train, y_test = train_test_split( 
    df2, target, test_size = 0.3, random_state = 100)

In [24]:
print(X_train)

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6
32  0  1    1    0    1    1    1    0    1    1    0    0  2    1    0    0
6   0  0    1    0    0    1    0    1    1    0    0    1  0    1    1    0
3   1  0    0    1    0    0    1    1    1    1    0    0  4    1    0    1
12  0  0    1    0    0    0    1    0    0    0    0    0  0    0    0    0
51  0  0    1    0    0    1    1    1    1    1    0    0  4    1    0    0
.. .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..  ...  ...  ...
79  0  0    1    0    0    0    1    1    1    1    0    0  0    1    0    0
87  0  0    1    0    0    0    0    0    0    1    0    0  6    0    0    0
67  1  0    0    1    0    0    1    1    1    1    0    0  4    1    1    1
24  0  0    1    0    0    1    1    1    1    1    0    0  4    0    0    0
8   1  0    0    1    0    0    0    1    1    1    0    0  4    0    1    0

[70 rows x 16 columns]


In [25]:
print(X_test)

    1  0  0.1  1.1  0.2  0.3  1.2  1.3  1.4  1.5  0.4  0.5  4  0.6  0.7  1.6
37  0  0    1    0    0    1    1    1    1    0    0    1  0    1    0    0
62  1  0    1    1    0    1    1    0    1    1    0    0  4    1    0    1
26  1  0    0    1    1    0    0    1    1    1    0    0  2    1    0    0
41  0  0    1    0    1    0    1    0    0    1    0    0  6    0    0    0
35  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    0
25  0  0    1    0    0    1    1    1    1    1    1    0  4    0    0    0
36  0  1    1    0    1    0    1    0    1    1    0    0  2    1    0    0
33  0  0    1    0    0    1    0    1    1    0    0    1  0    1    0    0
77  0  1    1    0    1    1    1    0    1    1    0    0  2    1    0    0
21  1  0    0    1    0    0    0    1    1    1    0    0  4    1    0    1
85  0  0    1    0    0    1    1    1    1    0    1    1  0    1    0    1
50  1  0    1    0    1    0    0    0    0    1    0    0  6    0    0    0

In [26]:
print(y_train)

32    2
6     4
3     1
12    7
51    5
     ..
79    3
87    6
67    1
24    5
8     1
Name: 1.7, Length: 70, dtype: int64


In [27]:
print(y_test)

37    4
62    1
26    1
41    6
35    1
25    5
36    2
33    4
77    2
21    1
85    4
50    6
92    1
69    1
96    6
78    2
72    4
5     1
40    2
11    4
29    6
83    1
82    2
43    1
28    1
22    2
23    6
90    3
86    2
20    2
Name: 1.7, dtype: int64


In [28]:
 clf_gini = DecisionTreeClassifier(criterion = "gini",
            random_state = 100,max_depth=3, min_samples_leaf=5)

In [29]:
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)

In [30]:
print(clf_gini)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=100)


In [31]:
clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 5)

In [32]:
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [33]:
print(clf_entropy)

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)


In [37]:
y_pred = clf_gini.predict(X_test)
print("Predicted values:")
print(y_pred)

Predicted values:
[4 1 1 7 1 7 2 4 2 1 4 7 1 1 7 2 4 1 2 4 7 1 2 1 1 2 7 7 2 2]


In [42]:
y1_pred = clf_entropy.predict(X_test)
print("Predicted values:")
print(y1_pred)

Predicted values:
[4 1 1 7 1 4 2 4 2 1 4 6 1 1 6 2 4 1 2 4 6 1 2 1 1 2 6 4 2 2]


In [49]:
print("Confusion Matrix: ",confusion_matrix(y_test, y1_pred))

Confusion Matrix:  [[10  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0  0  0  4  1]
 [ 0  0  0  0  0  0  0]]


In [50]:
print("Confusion Matrix: ",confusion_matrix(y_test, y_pred))

Confusion Matrix:  [[10  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  0]]


In [45]:
print ("Accuracy : ",accuracy_score(y_test,y1_pred)*100)

Accuracy :  90.0


In [46]:
print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)

Accuracy :  76.66666666666667


In [47]:
print("Report : ",classification_report(y_test, y1_pred))

Report :                precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         8
           3       0.00      0.00      0.00         1
           4       0.71      1.00      0.83         5
           5       0.00      0.00      0.00         1
           6       1.00      0.80      0.89         5
           7       0.00      0.00      0.00         0

    accuracy                           0.90        30
   macro avg       0.53      0.54      0.53        30
weighted avg       0.89      0.90      0.89        30



/home/root1/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/root1/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [48]:
print("Report : ",classification_report(y_test, y_pred))

Report :                precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         8
           3       0.00      0.00      0.00         1
           4       1.00      1.00      1.00         5
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         5
           7       0.00      0.00      0.00         0

    accuracy                           0.77        30
   macro avg       0.43      0.43      0.43        30
weighted avg       0.77      0.77      0.77        30

